### PR TITLE
update colors

### PR DESCRIPTION
**Pull request by rBatt**
http://colorbrewer2.org/?type=qualitative&scheme=Dark2&n=7

### CODE REVIEW

**Comment by rBatt** [comment]
@jread-usgs all i changed was color, all those checks should be fine.

small change from #87

**Comment by jread-usgs** [comment]
Still not a super big fan of how similar `MacItyre` and `Soloviev` look with this palette

**Comment by rBatt** [comment]
use this

c("#e41a1c","#377eb8","#4daf4a","#984ea3","#ff7f00","#ffff33","#a65628")

**Comment by jread-usgs** [comment]
image

**Comment by rBatt** [comment]
Did you use gray instead of that brownish color?

I'm trying for these colors:
http://colorbrewer2.org/?type=qualitative&scheme=Set1&n=7

Using gray might compromise the contrast for color blindness (i don't know
for sure though)

**Comment by jread-usgs** [comment]
I thought there were too many browns (3) in the palette, and no use of black or grey, which are two good contrast colors. judgement call. Also, prints better in grayscale.

**Comment by rBatt** [comment]
?? There's only 1 brown, right?

Maybe those colors aren't translating correctly ...

**Comment by jread-usgs** [comment]
I removed one, but there were what I would consider 3 shades of yellowy-browny colors. 7 lines is hard.

**Comment by rBatt** [comment]
Indeed. Looks good.

**Pull request merged**
