### PR TITLE
match.arg() for metab method

### PR DESCRIPTION
**Pull request by jread-usgs**
#85 @rBatt this is what I was talking about. specifying NULL for the arg then defaults to the first choice in the table.

### CODE REVIEW

**Comment by rBatt** [comment]
I see. I guess I was originally thinking that I didn't want to suggest a
"default" and I wanted to force the user to have to specify something. But
it doesn't really matter.

**Comment by jread-usgs** [comment]
Then remove the `=NULL` from `method=NULL` in the args. It will still give you a nice verbose error that includes all of the possible options.

**Comment by jread-usgs** [comment]
want me to change it?

**Comment by rBatt** [comment]
No, I like what you have. I agree that even if I don't want default
behavior your method is more elegant. I also now think that the default
behavior is reasonable anyway. Good call on making the default bookkeep – I
simply had alphabetic ordering before.

**Pull request merged**
