### PR TITLE
changing date labels

### PR DESCRIPTION
**Pull request by jzwart**
Inland Waters date convention is day abbreviated month year (e.g. 09 Jul 2009)

### CODE REVIEW

**Comment by lawinslow** [comment]
:+1: looks good. You can merge this if you're finished with all the changes for the IW publication.

**Comment by hdugan** [comment]
publication????

**Comment by lawinslow** [comment]
Word on the street is we're close.

**Comment by hdugan** [comment]
HALLELUJAH 🙏

**Pull request merged**
