### PR TITLE
Change sun.rise.set() output from matrix to data.frame

### PR DESCRIPTION
**Pull request by clnsmth**
This fix maintains the index order of returned sunrise/sunset values and the associated POSIX classes while adding the column names ‘sunrise’ and ‘sunset’. A search of the code base reveals this function is used by is.day() and add.night(), which index values according to order, therefore this fix does not break any linked processes within LakeMetabolizer.

Additionally, the calculation methods imply returned values in standard time. The function metadata now explicitly states this.

### CODE REVIEW

**Comment by jzwart** [comment]
Hi @clnsmth , thank you for submitting this PR and detailed notes in issue #127. Sorry for the delay in reviewing this. All looks good! I rebuilt locally and reproduced the output in the [demo figures](https://github.com/GLEON/LakeMetabolizer/tree/master/demo), which matched the results detailed in the [Winslow et al 2016 manuscript](https://www.tandfonline.com/doi/abs/10.1080/IW-6.4.883). Only issue is a conflict of the [`add_night` function](https://github.com/GLEON/LakeMetabolizer/blob/94e26ddd201be9f6058de0b2ae6ddb741166b2f7/demo/fig_k600.R#L76-L80) for the `k_600` figure, which throws an error with the new `data.frame` output. I'm [adding a PR ](https://github.com/clnsmth/LakeMetabolizer/pull/1) to your PR for suggested changes. And thank you for adding the tests to this package, that's good practice that we should expand upon for LakeMetabolizer. 

Merging this PR should close #127, but @clnsmth brings up a good issue with sunrise and sunset calculations in LakeMetabolizer - see #138 for more details.

**Comment by clnsmth** [comment]
OK @jzwart. Let me know if there's anything I can help with.

**Comment by jzwart** [comment]
@clnsmth, I think if you merge [my PR into yours](https://github.com/clnsmth/LakeMetabolizer/pull/1), then I can merge this one.

**Comment by clnsmth** [comment]
@jzwart, did that work?

**Comment by jzwart** [comment]
Yup looks good, thanks!

**Pull request merged**
